# Generated by Django 2.2.7 on 2022-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voc_nps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=30)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='brandlogos/')),
                ('is_accept', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('userqrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('qrcodename', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
            options={
                'db_table': 'voc_nps',
            },
        ),
    ]
