# Generated by Django 2.2.7 on 2022-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_nps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voc_nps',
            name='brand',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='voc_nps',
            name='link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='voc_nps',
            name='product',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='voc_nps',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='voc_nps',
            name='userqrcode',
            field=models.ImageField(blank=True, null=True, upload_to='userqrcodes/'),
        ),
    ]
