# Generated by Django 2.2.7 on 2022-06-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_nps', '0002_auto_20220526_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('scolor', models.CharField(blank=True, max_length=100, null=True)),
                ('rcolor', models.CharField(blank=True, max_length=100, null=True)),
                ('fcolor', models.CharField(blank=True, max_length=100, null=True)),
                ('bcolor', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
    ]
