# Generated by Django 2.2.7 on 2022-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_nps', '0004_auto_20220613_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='maintext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
