# Generated by Django 2.2.7 on 2022-06-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_nps', '0005_auto_20220613_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='template_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
