# Generated by Django 2.2.7 on 2022-06-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_nps', '0006_auto_20220613_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('product', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Rating_Report',
            },
        ),
    ]
