# Generated by Django 2.2.7 on 2022-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phonecode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
