# Generated by Django 2.2.7 on 2022-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_guestaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccount',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
