# Generated by Django 2.2.7 on 2022-04-15 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20220413_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
