# Generated by Django 2.2.7 on 2022-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20220415_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccount',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
