# Generated by Django 2.2.7 on 2022-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_auto_20220805_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datatype',
            field=models.CharField(default='Testing', max_length=100),
        ),
    ]
