# Generated by Django 2.2.7 on 2022-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_account_datatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=200)),
                ('url_ip', models.CharField(max_length=24)),
                ('others', models.CharField(max_length=2000)),
                ('url_id', models.CharField(default='BfPFN8oSZQpJfigtIlywFW', editable=False, max_length=300, unique=True)),
            ],
        ),
    ]
