# Generated by Django 2.2.7 on 2022-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=2000)),
                ('role', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=10)),
                ('dowell_time', models.CharField(max_length=30)),
                ('regional_time', models.CharField(max_length=30)),
                ('server_time', models.CharField(max_length=30)),
                ('userIP', models.CharField(max_length=200)),
                ('userOS', models.CharField(max_length=200)),
                ('userDevice', models.CharField(max_length=200)),
                ('userBrowser', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=50)),
                ('login_eventID', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='s0fSwGowcKfeN8d9JgZE1k', editable=False, max_length=300, unique=True),
        ),
    ]
