# Generated by Django 2.2.7 on 2022-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_auto_20221128_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsession',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='dowell_time',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='login_eventID',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='regional_time',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='server_time',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='userBrowser',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='userDevice',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='userIP',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='userOS',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='username',
        ),
        migrations.AddField(
            model_name='customsession',
            name='document',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsession',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='kXTQeyobdGOVWPwBlWNoYX', editable=False, max_length=300, unique=True),
        ),
    ]
