# Generated by Django 2.2.7 on 2022-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_auto_20221129_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='status',
            field=models.TextField(default='logout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='wNhmn9nVAsQMs09sl6z2Ax', editable=False, max_length=300, unique=True),
        ),
    ]
