# Generated by Django 2.2.7 on 2022-12-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0013_auto_20221203_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='vOcJgcSCmi13I8JxVnuS8G', editable=False, max_length=300, unique=True),
        ),
    ]
