# Generated by Django 2.2.7 on 2023-01-27 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_auto_20221203_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=2000)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='iBlpGcfXo9ejUG0iYLVXA2', editable=False, max_length=300, unique=True),
        ),
    ]
