# Generated by Django 2.2.7 on 2023-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0015_auto_20230127_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomsession',
            name='username',
            field=models.CharField(default='none', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='6uFSlNLh6HjfRQyGlozcJk', editable=False, max_length=300, unique=True),
        ),
    ]
