# Generated by Django 2.2.7 on 2023-02-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_auto_20230129_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_task',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='Snf2gIWE3y2NVq5Vh6lMO8', editable=False, max_length=300, unique=True),
        ),
    ]
