# Generated by Django 2.2.7 on 2023-02-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_auto_20230202_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrid', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='mT0DaXzUfaWzIhLzBc1mYQ', editable=False, max_length=300, unique=True),
        ),
    ]
