# Generated by Django 2.2.7 on 2023-02-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0018_auto_20230209_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='fBLk9bZBiUHgSAsVYiSFLo', editable=False, max_length=300, unique=True),
        ),
    ]
