# Generated by Django 2.2.7 on 2023-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0019_auto_20230209_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_creation',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='vn6Kd2qTClZYiaiqBsrEDK', editable=False, max_length=300, unique=True),
        ),
    ]
