# Generated by Django 2.2.7 on 2023-04-11 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0020_auto_20230209_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=20)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('sms', models.IntegerField(null=True)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='zzVQHO6u0VJZ3FHdBVtVky', editable=False, max_length=300, unique=True),
        ),
    ]
