# Generated by Django 2.2.7 on 2023-04-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0021_auto_20230411_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='76ZW826fOGj3DU2g66JV5B', editable=False, max_length=300, unique=True),
        ),
    ]
