# Generated by Django 2.2.7 on 2023-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0022_auto_20230411_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(max_length=1000)),
                ('date_updated', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='2MW3KcjrylaSQQbOEQB8A7', editable=False, max_length=300, unique=True),
        ),
    ]
