# Generated by Django 2.2.7 on 2023-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0023_auto_20230509_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Public_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(max_length=1000)),
                ('date_updated', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Live_QR_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrid', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(max_length=1000)),
                ('date_updated', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='rzKwSGDsXCClh9XzyKLa4D', editable=False, max_length=300, unique=True),
        ),
    ]
