# Generated by Django 2.2.7 on 2023-06-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0024_auto_20230515_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccount',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='VpegAdpBjHcKw72JeFISn3', editable=False, max_length=300, unique=True),
        ),
    ]
