# Generated by Django 2.2.7 on 2023-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0025_auto_20230601_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_qr_status',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='n1yxUUpVg359QwE1Rf3ApG', editable=False, max_length=300, unique=True),
        ),
    ]
