# Generated by Django 2.2.7 on 2023-06-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0026_auto_20230607_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_qr_status',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='TWTUPzWMI7UfGBMDlpxaQy', editable=False, max_length=300, unique=True),
        ),
    ]
