# Generated by Django 2.2.7 on 2023-06-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0027_auto_20230607_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_public_status',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='rqa0R7NPWkAqz0IyU1jEwj', editable=False, max_length=300, unique=True),
        ),
    ]
