# Generated by Django 2.2.7 on 2023-06-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0028_auto_20230607_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestatus',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestatus',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='w1cUM5qu8hFVe25JbuwcyC', editable=False, max_length=300, unique=True),
        ),
    ]
