# Generated by Django 2.2.7 on 2023-06-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0029_auto_20230607_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live_qr_status',
            old_name='date_updated',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='live_public_status',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='live_public_status',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='live_qr_status',
            name='date_created',
        ),
        migrations.AddField(
            model_name='live_public_status',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live_qr_status',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='gzVFAys0NKG73HPqPIaduD', editable=False, max_length=300, unique=True),
        ),
    ]
