# Generated by Django 2.2.7 on 2023-06-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0030_auto_20230607_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='OYbBWYXOJqwolePtwMwwdT', editable=False, max_length=300, unique=True),
        ),
    ]
