# Generated by Django 2.2.7 on 2023-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0031_auto_20230624_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkbased_RandomSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=1000)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='112tUPCq9lNFkMxbKhT0aR', editable=False, max_length=300, unique=True),
        ),
    ]
