# Generated by Django 2.2.7 on 2023-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0032_auto_20230713_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, unique=True)),
                ('usual', models.TextField()),
                ('unusual', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='m024coRr3xKs8LexfWlQgc', editable=False, max_length=300, unique=True),
        ),
    ]
