# Generated by Django 2.2.7 on 2023-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0033_auto_20230726_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=1000, unique=True)),
                ('url', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=1000)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='zs2pTJHSac0Q2GkT0iu12M', editable=False, max_length=300, unique=True),
        ),
    ]
