# Generated by Django 2.2.7 on 2023-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0034_auto_20230818_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='AmzPGmlhL4MA1zYn9fv6qd', editable=False, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ip',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
