# Generated by Django 2.2.7 on 2023-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0035_auto_20230818_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='ZMUpw7NjmwbMt2IkjVjwK8', editable=False, max_length=300, unique=True),
        ),
    ]
