# Generated by Django 2.2.7 on 2024-01-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0036_auto_20231221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkbased_randomsession',
            name='status',
            field=models.CharField(blank=True, default='logout', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='url_id',
            field=models.CharField(default='GDAyOW9RYWeylYNzaqvMOK', editable=False, max_length=300, unique=True),
        ),
    ]
