from django.urls import path
from api import views
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
urlpatterns=[
    path('',views.homeView),
    path('/token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('/hello/', views.MyView.as_view(), name='hello'),
    path('/rights/', views.rightsView.as_view(), name='rights'),
    # path('/register/', views.RegisterView.as_view(), name='register'),
    #path('/rating/', views.RatingView.as_view(), name='rating'),
    path('/login/', views.LoginView.as_view(), name='login'),
    path('/mobilelogin/', views.MobileLogin, name='mobilelogin'),
    path('/mobilelogout/',views.MobileLogout,name='mobilelogout'),
    path('/user/', views.UserView.as_view(), name='user'),
    path('/profile/', views.LoginUserView.as_view(), name='profile'),
    path('/adminuser/', views.UsrInfoView.as_view(), name='adminuser'),
    path('/hruser/', views.HrUserView.as_view(), name='hruser'),
    path('/users/', views.UsersView.as_view(), name='users'),
    path('/listusers/', views.userslist, name='listusers'),
    path('/company/', views.Company, name='company'),
    path('/linklogin/', views.LinkLogin, name='linklogin'),
    path('/createuser/', views.createUserView.as_view(), name='createuser'),
    path('/event/', views.EventView.as_view(), name='event'),
    path('/linkbased/', views.LinkBased, name='linkbased'),
    path('/logout/', views.LogoutView.as_view(), name='logout'),
    path('/update/<int:id>', views.UserUpdateView.as_view(), name='update'),

    path('/profile_view/',views.profile_view,name='profile_view'),
    path('/profile_update/',views.profile_update,name='profile_update'),
    path('/password_change/',views.password_change,name='password_change'),
    path('/registration/',views.Registration, name='registration'),
    path('/new_userinfo/',views.UserInfo, name='new_userinfo'),
    path('/userinfo/',views.new_userinfo,name="userinfo"),
    path('/all_users/',views.all_users,name="all_users"),
    path('/lastlogins/',views.lastlogins,name="lastlogins"),
    path('/activeusers/',views.activeusers,name="activeusers"),
    path('/live_users/',views.live_users,name="live_users"),
    path('/live_qr_users/',views.live_qr_users,name="live_qr_users"),
    path('/live_public_users/',views.live_public_users,name="live_public_users"),
    path('/all_liveusers/',views.all_liveusers,name="all_liveusers"),
    path('/product_users/',views.product_users,name="product_users"),
    path('/forgot_password/',views.forgot_password,name="forgot_password"),
    path('/forgot_username/',views.forgot_username,name="forgot_username"),
    path('/loginapi/',views.PublicApi,name="loginapi"),
    path('/logininfo/',views.logininfo,name="logininfo"),
    path('/register/',views.register, name='register'),
    path('/login_legal_policy/',views.login_legal_policy,name="login_legal_policy"),
    path('/linklogin_info/',views.linklogin_info,name="linklogin_info"),
    path('/login_init_api/',views.login_init_api,name="login_init_api"),
    path('/main_login/',views.main_login,name="main_login"),
    path('/main_logout/',views.main_logout,name="main_logout"),
    path('/removeaccount/',views.user_status,name="user_status"),
    path('/emailotp/',views.email_otp,name="emailotp"),
    path('/mobilesms/',views.mobilesms,name="mobilesms"),
    path('/otp_verify/',views.otp_verify,name="otp_verify"),
    path('/validate_username/', views.validate_username, name='validate-username'),
    path('/user_data/',views.user_data,name="user_data"),
    path('/user_report/',views.user_report,name="user_report"),
    path('/all_username/',views.all_username,name="all_username"),
    path('/face_login/',views.face_login,name="face_login"),
    path('/face_login_api/',views.face_login_api,name="face_login_api"),
    path('/face_id/',views.face_id,name="face_id"),
    path('/user_under_org/',views.user_under_org,name="user_under_org"),
    path('/master_login/',views.master_login,name="master_login")

]
